### ISSUE TITLE
You built exactly what i'm trying to build using Vue as a learning project!

### ISSUE THREAD

**Issue by Julianoe** [JakeOliger/Twitter-Friends-Manager#1]
In the README though you are talking about a script to fetch the .json file. Have you wrote it? Would you mind sharing it?

**Comment by JakeOliger** [comment]
Here, [these scripts may help](https://gist.github.com/JakeOliger/14703fbddfd565cf5970a365f12b8581). `list-followers.py` is the one you need to run the project, and `fetch-profile-images.py` is a simple script to nab all the profile images with a two second delay between each.

Sorry for the delayed reply -- haven't been checking my e-mail a lot this week.
